repos:
  # Fix end of files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
        files: '.*\.py$'
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - '--fix=lf'

  # Remove unused imports/variables
  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          - "--in-place"
          - "--remove-all-unused-imports"
          - "--remove-unused-variables"
          - "--exclude=__init__.py"

  # Sort imports
  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # Black formatting
  - repo: https://github.com/psf/black
    rev: "25.1.0"
    hooks:
      - id: black

  # Lint files
  - repo: https://github.com/pycqa/flake8
    rev: "7.0.0"
    hooks:
      - id: flake8
        args:
          - "--max-line-length=88"
          - "--ignore=E203,W503"
          - "--extend-ignore=E501"
          - "--exclude=__init__.py"

  # TODO Add running tests
