name: portfolio

x-common-env-postgres: &env-postgres
  POSTGRES_DB: ${POSTGRES_DB_INIT}
  POSTGRES_DB_BACKEND: ${POSTGRES_DB_BACKEND}
  POSTGRES_DB_GEOSERVER: ${POSTGRES_DB_GEOSERVER}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PORT: ${POSTGRES_PORT}
  POSTGRES_SSLMODE: ${POSTGRES_SSLMODE}

x-common-env-app-backend: &env-app-backend
  DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
  DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
  SECRET_KEY: ${SECRET_KEY}
  DEBUG: ${DEBUG}
  BASE_URL: ${BASE_URL}
  API_PATH: ${API_PATH}
  DJANGO_ADMIN_ENABLED: ${DJANGO_ADMIN_ENABLED}
  DJANGO_ADMIN_PATH: ${DJANGO_ADMIN_PATH}
  WAGTAIL_ADMIN_PATH: ${WAGTAIL_ADMIN_PATH}
  WAGTAIL_SITE_NAME: ${WAGTAIL_SITE_NAME}
  WAGTAILADMIN_BASE_URL: ${WAGTAILADMIN_BASE_URL}
  WAGTAILDOCS_EXTENSIONS: ${WAGTAILDOCS_EXTENSIONS}
  WAGTAILIMAGES_EXTENSIONS: ${WAGTAILIMAGES_EXTENSIONS}
  WAGTAILDOCS_SERVE_METHOD: ${WAGTAILDOCS_SERVE_METHOD}
  CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
  DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
  DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
  DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
  DJANGO_FLUSH_DB: ${DJANGO_FLUSH_DB}
services:
  db:
    build:
      context: ..
      dockerfile: .docker/Dockerfile.postgresql
    container_name: db
    hostname: db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ../postgres_data:/var/lib/postgresql/data
    environment:
      <<: *env-postgres
      TEST_DATA: ${TEST_DATA}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  app-backend:
    build:
      context: ..
      dockerfile: .docker/Dockerfile.backend
    container_name: app-backend
    image: app-backend-image
    hostname: app-backend
    restart: unless-stopped
    volumes:
      - ../backend:/srv/app
    depends_on:
      - db
    environment:
      <<: [*env-postgres, *env-app-backend]
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"


