# Use an official Node runtime as a parent image
FROM node:20-alpine

# Set the working directory
WORKDIR /srv/app

# Copy package.json and package-lock.json
COPY ../frontend/package*.json /srv/app

COPY ../frontend/tsconfig*.json /srv/app

# Install dependencies
RUN npm install

# Copy the current directory contents into the container
COPY ../frontend /srv/app

# Build the React app
RUN npm run build

# Expose the port the app runs on
EXPOSE 5173 6006

